export const elements = {
	hoverversionhistory: "//div[@id='radix-:r36:']",
	stepversioningcreated: "//div[contains(text(),'v(2) 2023-Nov-03')]",
	meatballicon:"//button[@aria-label='Step body more actions']//span[@aria-label='Dots']//*[name()='svg']",
	submitWorkflowStep:"//span[contains(text(),'Submit')]",
	workflowinputfield:"//span[@class='ant-legacy-form-item-children']//textarea[1]",
	workflowstep:"//div[@class='css-z0krbk-Stack']",
	studioBtn: "//span[contains(text(),'Studio')]",
	createNewMessage: "//span[contains(text(),'Create New...')]",
	helloUserMessage: "//*[contains(text(),'Hello')]",
	welcomeMessage: "//*[contains(text(),'this is arg. How can we help you today?')]",
	searchField: "//div[contains(text(),'Select...')]",
	helpButton: "//button[@aria-label='Help']",
	recentlyViewed: "//span[contains(text(),'RECENTLY VIEWED')]",
	recentlyViewedWorkflow: "(//section[@aria-label='Recently Viewed']/a/div/span)[1]",
	tenantLogo: "(//a[@href='/home'])[1]",
	homeButton: "(//a[@href='/home'])[2]",
	starredWorkflow: "(//button[@aria-label='Remove starred process']/parent::div/following-sibling::a)[1]",
	userProfileDropdown: "//div[@aria-label='User profile']/div",
	userProfileDropdownOption: "//div[@role='menuitem']/div/div[contains(text(),'arg')]",
	waitingOnYouButton: "//button[@aria-label='Waiting on you']",
	requestedByYouButton: "//button[@aria-label='Requested by you']",
	processTable: "//table[@aria-label='My Process Report']",
	processTableHeaders: "//th[@aria-label='arg']",
	processTableHeadersSortButton: "//th[@aria-label='arg']/div/span/div/span[2]",
	processTabelHeaderFilterButton: "//th[@aria-label='arg']/div/span[2]",
	processTableAllRows: "//tbody/tr",
	processTableFirstName: "(//tbody/tr/td[1]/div/div/div[1]/div)[1]",
	processTableFirstProgress: "//tbody/tr[2]/td[4]",
	processTableAllProcessName: "//tbody/tr/td[1]/div/div/div[1]",
	processTableAllStatus: "//tbody/tr/td[2]/div/div",
	processTableRow: "//tbody/tr[2]/td[1]",
	paginationMessage: "//li[@class='ant-pagination-total-text']",
	paginationNextButton: "//li[@title='Next Page']/button",
	paginationPage1: "//li[@title='1']/a",
	tasksCountBandge: "//a[@href='/tasks']/div/div/span",
	filterSearchInputField: "//input[@placeholder='arg']",
	filtersearchButton: "(//button[@aria-label='Search'])[1]",
	filterResetbutton: "(//button[@aria-label='Reset'])[arg]",
	statusFilterCheckbox: "//input[@aria-label='arg']",
	appliedFilters: "//*[contains(text(),'Filters')]/following-sibling::div/div",
	clearFilterButton: "//button[@data-testid='clear-filters']",
	noResult: "//div[contains(text(),'No data/findings')]",
	createNewButton: "//button[@aria-label='Create new']",
	createNewSearch: "//input[@role='menuitem']",
	createNewSearchResult: "//div[@role='menuitem'][text()='?']",
	userMentionsIcon: "//*[@aria-label='Mentions']",
	userMentionsBadge: "//span[@aria-label='Mentions']/parent::div/parent::button/preceding-sibling::span",
	totalMentionsBadge: "//div[contains(text(),'My mentions')]/div",
	searchViewAsUserInput: "//input[@role='menuitem' and @placeholder='Search Users...']",
	spanContainsText: "//span[contains(text(),'arg')]",
	viewingAsUser: "//span[contains(text(),'Viewing as')]/following-sibling::div",
	recentComment: "//span[contains(text(),'@Home Automation')]/parent::span[contains(text(),' 2023-08-30 11:03:05')]",
	statusModal: "//div[@role='document']",
	stepNode: "//div[starts-with(@class,'custom-node')]",
	stepNodeExpanded: "//div[starts-with(@class,'custom-node-expanded')]",
};
