export const elements = {
	workFlowNameLabel: "//span[contains(text(),'arg')]/following-sibling::span[contains(text(),'(#')]",
	allTaskslabel: "//span[contains(text(),'All Tasks')]",
	stepBody: "//div[@id='StepBody']",
	progressBarCircle: "//div[@data-testid='progress-bar-circle']",
	commentHistory: "(//span[@aria-label='Messages'])[1]",
	stepLevelComment: "(//span[@aria-label='Messages'])[2]",
	fieldLevelComment: "(//span[@aria-label='Messages'])[3]",
	commentPanelIcon: "//div[contains(@class,'message-count')]",
	viewLogDiv: "((//ul[starts-with(@class,'ant-timeline')])[2]/li/div[3])",
	significantEventLogDiv: "((//ul[starts-with(@class,'ant-timeline')])[1]/li/div[3])",
	emailLogDiv: "((//ul[starts-with(@class,'ant-timeline')])[4]/li/div[3])",
	editsLogDiv: "((//ul[starts-with(@class,'ant-timeline')])[3]/li/div[3])",
	stepSpan: "//div[@class='ant-collapse-content-box']/..//span[contains(text(),'arg')]",
	childTable: "//span[contains(@class,'list-title-header') and contains(text(),'arg')]",
	ChildWorkflowSideViewHeader: "(//span[@aria-label='ChevronRight']//parent::span)[3]",
	sidePanelCloseIcon: "//span[@aria-label='Close']",
	discardDialogueBox: "//div[@class='ant-modal-content']",
	workflowFields:
		"//*[contains(text(),'arg')]/ancestor::div[4]/following-sibling::div/..//*[@class='ant-input' or @class='ant-input-number-input']",
	childTableRowCount: "//span[@aria-label='list-count']//p[@class='ant-scroll-number-only-unit current']",
	disabledElements: "//*[@disabled]",
	childTableRowData:
		"//span[text()='arg']//parent::span//ancestor::tr//td[@class='ant-table-cell ant-table-cell-ellipsis']",
	childWorkflowTableHeadersSortButton: "//div[text()='arg']/ancestor::span[1]/following-sibling::span",
	childTableAllProcessName: "//tbody/tr/td/span",
	childTableAllProcessAgeField: "//tbody/tr/td[3]",
	childTableAllProcessNameCTPField: "//tbody/tr/td[6]",
	childTableAllProcessEmailField: "//tbody/tr/td[4]",
	childTableAllProcessMotherNameField: "//tbody/tr/td[2]",
	childWorkflowTableFilterButton:
		"//div[text()='arg']/ancestor::span/following-sibling::span[@class='ant-table-filter-trigger-container']",
	childWorkflowTableFilterInputField: "//span[text()='arg']//preceding-sibling::input",
	childWorkflowTableFilterSearchButton: "//span[text()='Search']",
	childWorkflowTableFilterResetButton: "//span[text()='Reset']",
	childWorkflowTableSearchInputField: "//input[@placeholder='arg']",
	workflowStatus:
		"(//*[@data-testid='progress-bar-circle' or @aria-label='Checkmark'])[1]/parent::div/following-sibling::div",
};
